// Generated by CoffeeScript 1.7.1
var path;

path = require("path");

module.exports = function(grunt) {
  grunt.initConfig({
    pkg: grunt.file.readJSON("package.json"),
    meta: {
      version: "<%= pkg.version %>",
      core_banner: "// ExtM (Extende Marionette)\n",
      banner: "<%= meta.core_banner %>\n" + "/*!\n"
    },
    clean: {
      lib: "lib",
      tmp: "tmp"
    },
    plato: {
      extm: {
        src: "src/**/*.js",
        dest: "reports",
        options: {
          jshint: grunt.file.readJSON(".jshintrc")
        }
      }
    },
    docker: {
      extm: {
        src: ["src/**/*.coffee"],
        dest: "docs"
      }
    },
    jshint: {
      options: {
        jshintrc: ".jshintrc"
      },
      marionette: ["src/**/*.js"]
    },
    lintspaces: {
      all: {
        src: ["src/**/*.coffee", "src/**/*.js", "docs/*.md"],
        options: {
          editorconfig: ".editorconfig"
        }
      }
    },
    preprocess: {
      core_build: {
        src: 'src/build/extm.core.js',
        dest: 'lib/extm.core.js'
      },
      test_file: {
        src: 'src/build/extm.core.js',
        dest: 'tmp/extm.core.js'
      },
      test_file_amd: {
        src: 'src/build/extm.amd.js',
        dest: 'tmp/extm.amd.js'
      },
      amd: {
        src: 'src/build/extm.amd.js',
        dest: 'lib/extm.amd.js'
      }
    },
    karma: {
      configFile: 'spec/karma.conf.js',
      runnerPort: 9999,
      singleRun: false,
      browsers: ['PhantomJS'],
      logLevel: 'ERROR'
    },
    jasmine: {
      EXTM: {
        src: ['bower_components/underscore/underscore.js', 'bower_components/jquery/dist/jquery.js', 'bower_components/backbone/backbone.js', 'bower_components/marionette/lib/backbone.marionette.js', 'bower_components/mustache/mustache.js', 'bower_components/async/lib/async.js', 'bower_components/jquery.validation/dist/jquery.validate.js', 'bower_components/jasmine-ajax/lib/mock-ajax.js', 'bower_components/jasmine-jquery/lib/jasmine-jquery.js', 'tmp/extm.core.js'],
        options: {
          specs: 'spec/javascripts/**/*jspec.js',
          helpers: 'spec/javascripts/helpers/*.js'
        }
      }
    },
    watch: {
      extmtestbuild: {
        files: ['src/**/*.coffee'],
        tasks: ['preprocess:test_file_amd']
      }
    }
  });
  require("matchdep").filterDev("grunt-*").forEach(grunt.loadNpmTasks);
  return grunt.registerTask("verify-bower", function() {
    if (!grunt.file.isDir("./bower_components")) {
      return grunt.fail.warn("Missing bower components. You should run `bower install` before.");
    }
  });
};
