// Generated by CoffeeScript 1.7.1
describe('Extm abstract form view', function() {
  it('must be defined', function() {
    expect(Extm.FormView).toBeDefined();
    return expect(Extm.FormView).toEqual(jasmine.any(Function));
  });
  return it('must extend from marionette.itemview', function() {
    return expect(Extm.FormView.prototype.serializeData).toEqual(jasmine.any(Function));
  });
});
