// Generated by CoffeeScript 1.7.1
describe('Extm message bus', function() {
  return it('must be defined', function() {
    expect(window.msgbus).toBeDefined();
    return expect(window.msgbus).toEqual(jasmine.any(Object));
  });
});
