// Generated by CoffeeScript 1.7.1
define(['marionette', 'src/extm.application'], function(Marionette) {
  return describe("Extended marionette application", function() {
    var app;
    app = null;
    beforeEach(function() {
      app = new Marionette.Application;
      return app.startHistory();
    });
    afterEach(function() {
      Backbone.history.stop();
      return app = null;
    });
    describe("get current route", function() {
      return it("must return exact current route", function() {
        app.navigate("some-route", {
          trigger: true
        });
        return expect(app.getCurrentRoute()).toBe("some-route");
      });
    });
    return describe("navigate route", function() {
      return it("mus trigger a new route", function() {
        app.navigate("some-route", {
          trigger: true
        });
        return expect(app.getCurrentRoute()).toBe("some-route");
      });
    });
  });
});
