// Generated by CoffeeScript 1.7.1
define(['marionette', 'src/extm.marionette.regioncontroller'], function(Marionette) {
  return describe("Extended Marionette region controller", function() {
    describe("when creating a new controller without a region", function() {
      return it("must throw an error", function() {
        return expect(Marionette.RegionController.extend()).toThrow();
      });
    });
    return describe("On initialization", function() {
      var regionController;
      regionController = {};
      beforeEach(function() {
        return regionController = new Marionette.RegionController;
      });
      return it("must just work!!!", function() {
        return expect(regionController).toBeDefined();
      });
    });
  });
});
