// Generated by CoffeeScript 1.7.1
define(['backbone', 'src/extm.backbone.model'], function(Backbone) {
  window.AJAXURL = '';
  return describe("Backbone Model to support wordpress", function() {
    var handleRequest;
    handleRequest = jasmine.createSpy("handleRequest");
    describe("model create", function() {
      var model;
      model = {};
      beforeEach(function() {
        var Model;
        Model = Backbone.Model.extend({
          name: 'model'
        });
        model = new Model;
        return model.on('create:request', handleRequest);
      });
      afterEach(function() {
        return model = {};
      });
      it("on save for creating a model", function() {
        spyOn(model, "sync");
        model.save({});
        return expect(model.sync).toHaveBeenCalled();
      });
      it("must trigger a GET request", function() {
        var xhr;
        xhr = model.save({});
        console.log(xhr);
        return expect(xhr).toBeDefined();
      });
      return it("it must trigger the create:request event", function() {
        model.save({});
        return expect(handleRequest).toHaveBeenCalled();
      });
    });
    return describe("model update", function() {
      var model;
      model = {};
      beforeEach(function() {
        var Model;
        Model = Backbone.Model.extend({
          name: 'model'
        });
        model = new Model({
          id: 23
        });
        return model.on('update:request', handleRequest);
      });
      afterEach(function() {
        return model = {};
      });
      return it("it must trigger the update:request event", function() {
        model.save({});
        return expect(handleRequest).toHaveBeenCalled();
      });
    });
  });
});
