// Generated by CoffeeScript 1.7.1
define(['src/extm.namespace'], function(Extm) {
  return describe('Extm Namespace', function() {
    return it('must be defined', function() {
      expect(Extm).toBeDefined();
      return expect(Extm).toEqual(jasmine.any(Object));
    });
  });
});
