// Generated by CoffeeScript 1.7.1
define(['marionette', 'src/extm.application'], function(Marionette) {
  return describe('Extended marionette application', function() {
    return describe('when application starts', function() {
      var App;
      App = null;
      beforeEach(function() {
        spyOn(Backbone.history, 'start').and.callThrough();
        App = new Marionette.Application;
        return App.start();
      });
      afterEach(function() {
        return App = null;
      });
      return it("must start backbone history", function() {
        return expect(Backbone.history.start).toHaveBeenCalled();
      });
    });
  });
});
