// Generated by CoffeeScript 1.7.1
define(['src/extm.namespace'], function(Extm) {
  return describe('Extm namsepace', function() {
    return it('must have all objects defined', function() {
      return expect(Extm.Application).toBeDefined();
    });
  });
});
