// Generated by CoffeeScript 1.7.1
define(['src/extm.msgbus'], function(msgbus) {
  return describe('global msgbus', function() {
    it('must be defined and must be an object', function() {
      expect(msgbus).toBeDefined();
      expect(msgbus).toEqual(jasmine.any(Object));
      expect(msgbus.execute).toEqual(jasmine.any(Function));
      expect(msgbus.request).toEqual(jasmine.any(Function));
      return expect(msgbus.event.trigger).toEqual(jasmine.any(Function));
    });
    it('must have a handler', function() {
      return expect(msgbus.commands.hasHandler('when:fetched')).toBeTruthy();
    });
    return describe('msgbus fetch handler', function() {
      var commandHandler;
      commandHandler = null;
      beforeEach(function() {
        commandHandler = jasmine.createSpy('command:handler:callback');
        return msgbus.execute('when:fetched', [], commandHandler);
      });
      return it('must execute the passed callback function', function() {
        expect(commandHandler).toHaveBeenCalled();
        return expect(commandHandler.calls.count()).toBe(1);
      });
    });
  });
});
