// Generated by CoffeeScript 1.7.1
define(['src/extm.global.notification.controller'], function(NotificationController) {
  return describe('Global notification controller', function() {
    var notificationController;
    notificationController = null;
    return describe('on initialization', function() {
      beforeEach(function() {
        spyOn(NotificationController.prototype, 'initialize').and.callThrough();
        return notificationController = new NotificationController();
      });
      return afterEach(function() {
        return notificationController = {};
      });
    });
  });
});
