// Generated by CoffeeScript 1.7.1
define(['src/extm.marionette.renderer', 'marionette'], function(Renderer, Marionette) {
  return describe('marionette renderer', function() {
    describe('when given a template', function() {
      return it('must return the template', function() {
        var view;
        view = Marionette.Renderer.render('<div>Template</div>');
        return expect(view).toBe('<div>Template</div>');
      });
    });
    describe('when given a template and data', function() {
      return it('must return the template', function() {
        var data, view;
        data = {
          data: 'foo'
        };
        view = Marionette.Renderer.render('<div>{{data}}</div>', data);
        return expect(view).toBe('<div>foo</div>');
      });
    });
    return describe('when view runs render method', function() {
      var View, view;
      View = Marionette.ItemView.extend({
        template: '{{data}}'
      });
      view = new View({
        model: new Backbone.Model({
          data: 'foo'
        })
      });
      return it('must return proper template data', function() {
        return expect(view.render().$el.text()).toBe('foo');
      });
    });
  });
});
