// Generated by CoffeeScript 1.7.1
define('plugin-loader', [''], function() {});

define('apps-loader', [''], function() {});

define('extm', ['src/extm.namespace'], function(Extm) {
  return Extm;
});

define(['plugin-loader', 'apps-loader', 'extm'], function(plugins, apps, Extm) {
  var App;
  App = new Extm.Application;
  App.addRegions({
    headerRegion: '#header-region',
    leftNavRegion: '#left-nav-region'
  });
  App.onStart = function() {};
  App.setDefaultRoute('#/home');
  return App.start();
});
