// Generated by CoffeeScript 1.7.1
define(['../../src/extm.application'], function(Application) {
  Application.onStart = function() {};
  Application.setDefaultRoute('//home');
  return Application.start({
    regions: {
      headerRegion: '#header-region',
      leftNavRegion: '#left-nav-region'
    }
  });
});
