// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

require(['extm'], function(Extm) {
  var Rv, V;
  window.App = new Extm.Application;
  App.addRegions({
    headerRegion: '#header-region'
  });
  V = (function(_super) {
    __extends(V, _super);

    function V() {
      return V.__super__.constructor.apply(this, arguments);
    }

    V.prototype.template = 'hello world';

    return V;

  })(Marionette.ItemView);
  Rv = (function(_super) {
    __extends(Rv, _super);

    function Rv() {
      return Rv.__super__.constructor.apply(this, arguments);
    }

    Rv.prototype.initialize = function(options) {
      return this.show(new V);
    };

    return Rv;

  })(Extm.RegionController);
  App.start();
  return new Rv({
    region: App.headerRegion
  });
});
