// Generated by CoffeeScript 1.7.1
define(['marionette', 'backbone', 'jquery'], function(Marionette, Backbone, $) {
  var msgbus;
  msgbus = Backbone.Wreqr.radio.channel('global');
  msgbus.execute = function() {
    return msgbus.commands.execute.apply(msgbus.commands, arguments);
  };
  msgbus.request = function() {
    return msgbus.commands.execute.apply(msgbus.reqres, arguments);
  };
  msgbus.event = msgbus.vent;
  msgbus.commands.setHandler('when:fetched', function(deffereds, callback) {
    return $.when.apply($, deffereds).done(function() {
      return callback();
    });
  });
  return msgbus;
});
